### ISSUE TITLE
Todo Communication

### ISSUE THREAD

**Issue by floriankick** [packmas13/trotzdem13#118]
- [x] Bugfix: Link to banner not displayed at post
- [x] Change Label: Challenge -> Projekt
- [x] Show Reactions (missed that, sorry)
- [x] Edit functionality
- [x] Images
- [ ] Hashtags
- [ ] Publishing of posts to the public page
- [ ] Rich text (or at least some emoticons)
- [ ] Different reaction types (already planned in the database)
- [x] Show names with reactions
- [ ] Filter by banner, project, hashtag, team, ...
